### ISSUE TITLE
Render does not start together with the main one

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [chunky-dev/chunky-denoiser#25]
When the render is launched, the normal render is not launched together and the albedo renderer starts immediately with the main one.

Logs: 
```
Settings loaded from C:\Users\v124m\.chunky\chunky.json
Could not find image: textures/soul_fire.png
Could not find image: textures/soul_fire.png
Found Minecraft directory C:\Users\v124m\AppData\Roaming\.minecraft
Found latest Minecraft version: C:\Users\v124m\AppData\Roaming\.minecraft\versions\1.17.1-OptiFine_HD_U_H1_pre6\1.17.1-OptiFine_HD_U_H1_pre6.jar
Loading 842 textures from C:\Users\v124m\AppData\Roaming\.minecraft\versions\1.17.1-OptiFine_HD_U_H1_pre6\1.17.1-OptiFine_HD_U_H1_pre6.jar
Loading plugin: "chunky-discord.jar"
The plugin Discord Plugin was developed for Chunky 2.0-beta6 but this is Chunky 2.4.0 - it may not work properly.
DISCORD REGISTERED
Building new octree (PACKED)
Building new octree (PACKED)
Building new octree (PACKED)
Building new octree (PACKED)
Plugin chunky-discord.jar failed to load.
java.lang.NoSuchMethodError: se.llbit.chunky.renderer.RenderController.getRenderer()Lse/llbit/chunky/renderer/Renderer;
	at de.lemaik.chunky.discord.DiscordPlugin.attach(DiscordPlugin.java:52)
	at se.llbit.chunky.main.Chunky.lambda$loadPlugins$5(Chunky.java:269)
	at se.llbit.chunky.plugin.ChunkyPlugin.load(ChunkyPlugin.java:90)
	at se.llbit.chunky.main.Chunky.loadPlugins(Chunky.java:259)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:213)

Plugin loaded: Discord Plugin 1.0.0
Loading plugin: "chunky-denoiser.jar"
Plugin loaded: DenoiserPlugin 0.4.0
Settings loaded from C:\Users\v124m\.chunky\chunky-launcher.json
Saved settings to C:\Users\v124m\.chunky\chunky.json
[Discord] Connected to SPAWNRYS#1069
Building new octree (PACKED)
Building new octree (PACKED)
Loading render dump: C:\Users\v124m\.chunky\scenes\Titania\Titania.dump
Render dump loaded: Titania.dump
Loading octree Titania.octree2
Loading octree (PACKED)
Loading octree (PACKED)
Octree loaded
Built SAH_MA BVH with depth 17
Loading textures: [minecraft:leather_helmet]
Loading textures: [minecraft:leather_chestplate]
Loading textures: [minecraft:leather_leggings]
Loading textures: [minecraft:leather_boots]
Loading textures: [minecraft:leather_helmet]
Loading textures: [minecraft:leather_chestplate]
Loading textures: [minecraft:leather_leggings]
Loading textures: [minecraft:leather_boots]
Loading textures: [minecraft:diamond_helmet]
Loading textures: [minecraft:diamond_chestplate]
Loading textures: [minecraft:diamond_leggings]
Loading textures: [minecraft:diamond_boots]
Loading textures: [minecraft:golden_helmet]
Loading textures: [minecraft:golden_chestplate]
Loading textures: [minecraft:golden_leggings]
Loading textures: [minecraft:golden_boots]
Loading textures: [minecraft:turtle_helmet]
Loading textures: [minecraft:netherite_leggings]
Loading textures: [minecraft:chainmail_boots]
Built SAH_MA BVH with depth 13
Exception in thread "Thread-8" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = Thread-8
	at com.sun.glass.ui.Application.checkEventThread(Application.java:447)
	at com.sun.glass.ui.View.getNativeView(View.java:449)
	at com.sun.glass.ui.win.WinAccessible.get_HostRawElementProvider(WinAccessible.java:672)
	at com.sun.glass.ui.win.WinAccessible.UiaRaiseAutomationEvent(Native Method)
	at com.sun.glass.ui.win.WinAccessible.sendNotification(WinAccessible.java:287)
	at javafx.scene.Node.notifyAccessibleAttributeChanged(Node.java:9615)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:726)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:735)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:656)
	at se.llbit.chunky.ui.ChunkyFxController.showRenderPreview(ChunkyFxController.java:219)
	at se.llbit.chunky.ui.ChunkyFxController.lambda$null$1(ChunkyFxController.java:345)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-8" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = Thread-8
	at com.sun.glass.ui.Application.checkEventThread(Application.java:447)
	at com.sun.glass.ui.View.getNativeView(View.java:449)
	at com.sun.glass.ui.win.WinAccessible.get_HostRawElementProvider(WinAccessible.java:672)
	at com.sun.glass.ui.win.WinAccessible.UiaRaiseAutomationEvent(Native Method)
	at com.sun.glass.ui.win.WinAccessible.sendNotification(WinAccessible.java:287)
	at javafx.scene.Node.notifyAccessibleAttributeChanged(Node.java:9615)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:726)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:735)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:656)
	at se.llbit.chunky.ui.ChunkyFxController.showRenderPreview(ChunkyFxController.java:219)
	at se.llbit.chunky.ui.ChunkyFxController.lambda$null$1(ChunkyFxController.java:345)
	at java.lang.Thread.run(Unknown Source)
Saved settings to C:\Users\v124m\.chunky\chunky.json
Saved settings to C:\Users\v124m\.chunky\chunky.json
```

**Comment by leMaik** [comment]
You need at least [https://github.com/chunky-dev/chunky-denoiser/releases/tag/v0.4.0](v0.4.0) for Chunky 2.4 or later.
