### ISSUE TITLE
[2.5.0-snapshot] java.lang.NoSuchMethodError when using `DenoisedPathTracer`

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky-denoiser#32]
Tested on `2.5.0-snapshot.186.gf0535f2` with #30 

Select `DenoisedPathTracer`, hit `Start`

```
Unchecked exception in render manager.
java.lang.NoSuchMethodError: 'void se.llbit.chunky.renderer.scene.Scene.saveFrame(java.io.File, se.llbit.chunky.renderer.export.PictureExportFormat, se.llbit.util.TaskTracker, int)'
	at de.lemaik.chunky.denoiser.DenoisedPathTracingRenderer.render(DenoisedPathTracingRenderer.java:90)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:313)
```

**Comment by leMaik** [comment]
Fixed in v0.5.0-pre2 and (with #30 merged) in v0.5.0-pre3
