### ISSUE TITLE
Chunky Snapshot Latest with v0.5.0-pre1

### ISSUE THREAD

**Issue by carterlasalle** [chunky-dev/chunky-denoiser#47]
Unchecked exception in render manager.
java.lang.NoSuchFieldError: width
	at de.lemaik.chunky.denoiser.MultiPassRenderer.renderPass(MultiPassRenderer.java:13)
	at de.lemaik.chunky.denoiser.DenoiserPassRenderer.render(DenoiserPassRenderer.java:79)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:319)

**Comment by leMaik** [comment]
Thanks for reporting this, this issue is now fixed. Note that v0.4.x also works for Chunky 2.5.0 snapshots, I try to keep that version working for Chunky 2.4.x *and* 2.5.0 until 2.5.0 is released.
